#!/bin/zsh
set -euo pipefail
set -xv

uhub() {
    local a=${1:?}
    local hub=${2:?}
    local port=${3:?}
    cmd=(
            uhubctl
            -a $a
            -R
            -l $hub
            -p $port
            -e
            -N
        )
    $cmd
}

# Power cycle a specific hub/port
cycle() {
    local usb3_hub=${1:?}
    local usb2_hub=${2:?}
    local port=${3:?}

    # To power cycle properly, need to turn off the corresponding USB2 first
    uhub off $usb2_hub $port
    uhub off $usb3_hub $port
    uhub on $usb3_hub $port
    uhub on $usb2_hub $port

    # To activate the hub properly, need to run uhubctl once
    uhubctl -N -l $usb3_hub -p $port -e 
}

"$1" "${@:2}"
